const QueryKeys = {
  PAGINATED_STORES: "/paginated/stores",
  PAGINATED_CATEGORIES: "/paginated/categories",
  PAGINATED_VARIANT_TYPES: "/paginated/variant-types",
  PAGINATED_PRODUCTS_RECOMENDATION: "/paginated/products/recomendation",
  PAGINATED_USER_TRANSACTIONS: "/paginated/orders/user_transactions",
  PAGINATED_USER_ORDERS: "/paginated/orders/user_orders",
  PAGINATED_STORE_ORDERS: "/paginated/orders/store_orders",
  PAGINATED_STORE_WITHDRAWS: "/paginated/withdraws/store_withdraws",
  PAGINATED_WITHDRAWS: "/paginated/withdraws",
  PAGINATED_USER_REVIEWS: "/paginated/reviews/user_reviews",
  STORE_ORDERS: "/orders/store_orders",
  USER_ORDERS: "/orders/user_orders",
  ALL_CATEGORIES: "/categories",
  USER_STORE: "/users/user_store",
  USER_PROFILE: "/auth/me",
  PRODUCTS: "/products",
  STORE_GET_PROVINCE: "/stores/get_province",
  STORE_GET_CITES: "/stores/get_cities",
  STORE_BANNERS: "/stores/banners",
  STORE_CATEGORIES: "/stores/categories",
  LOGISTIC_COST: "/logistic/costs",
  USER_NOTIFICATIONS: "/notifications",
  USER_NOTIFICATIONS_COUNT: "/notifications/count",
};

export default QueryKeys;
